FRONT_END_BINARY=frontAPP
BROKER_BINARY=brokerApp
AUTH_BINARY=authApp

up:
	@echo "Starting Docker images..."
	docker compose up -d
	@echo "Docker images started!"

up_build: build_broker build_auth
	@echo "Stopping docker images (if running...)"
	docker compose down
	@echo "Building (when required) and Starting docker images...."
	docker compose up --build -d
	@echo "Docker images built and started!"

down:
	@echo "Stopping docker compose...."
	docker compose down
	@echo "Done!"

build_broker:
	@echo "Building broker binary"
	cd ../broker-service && env GOOS=linux CGO_ENABLED=0 go build -o ${BROKER_BINARY} ./cmd/api
	@echo "Done!"

build_auth:
	@echo "Building auth binary"
	cd ../authentication-service && env GOOS=linux CGO_ENABLED=0 go build -o ${AUTH_BINARY} ./cmd/api
	@echo "Done!"

build_front:
	@echo "Building front end binary..."
	cd ../front-end && env CGO_ENABLED=0 go build -o ${FRONT_END_BINARY} ./cmd/web
	@echo "Done!"

## start: starts the front end
start: build_front
	@echo "Starting front end"
	cd ../front-end && ./${FRONT_END_BINARY} &

## stop: stop the front end
stop:
	@echo "Stopping front end..."
	@-pkill -SIGTERM -f "./${FRONT_END_BINARY}"
	@echo "Stopped front end!"

